# --- FILE: .github/workflows/release-builder.yml (FINAL & ROBUST VERSION) ---
# This workflow automates the cross-platform compilation of the self-contained
# 'libnewrllama' dynamic library and attaches it to a GitHub Release.

name: Build and Release Pre-compiled Libraries

# This workflow is triggered whenever a new Release is 'published' on GitHub.
# It will not run on drafts or pre-releases.
on:
  release:
    types: [published]

jobs:
  # The main build job, which runs for each platform defined in the matrix.
  build:
    # A user-friendly name for the job, e.g., "Build for Linux (x64)"
    name: Build for ${{ matrix.os_name }}

    # The "matrix" strategy creates parallel jobs for each combination of settings.
    strategy:
      # We set fail-fast to false, so if one platform fails, the others will continue.
      fail-fast: false
      matrix:
        # Define our target platforms.
        include:
          - os: ubuntu-latest
            os_name: Linux
            artifact_name: libnewrllama_linux_x64.zip
            lib_name: libnewrllama.so
          - os: windows-latest
            os_name: Windows
            artifact_name: newrllama_windows_x64.zip
            lib_name: newrllama.dll
          - os: macos-13
            os_name: macOS (Intel)
            artifact_name: libnewrllama_macos_x64.zip
            lib_name: libnewrllama.dylib
          - os: macos-14
            os_name: macOS (Apple Silicon)
            artifact_name: libnewrllama_macos_arm64.zip
            lib_name: libnewrllama.dylib

    # Specify the virtual machine environment for the job.
    runs-on: ${{ matrix.os }}

    steps:
    # Step 1: Check out your repository's code.
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # This is crucial for pulling in the llama.cpp source code.
        submodules: 'recursive'

    # Step 2: Install platform-specific build dependencies.
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake curl libcurl4-openssl-dev

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      # vcpkg is a C++ package manager that simplifies getting dependencies on Windows.
      # We use it to get 'curl'.
      run: vcpkg install curl:x64-windows-static

    # macOS and Windows runners usually have CMake and compilers pre-installed.
    - name: Echo environment details
      run: |
        echo "Running on ${{ runner.os }}"
        cmake --version

    # Step 2.5: Copy custom files to llama.cpp directory
    - name: Copy custom files to llama.cpp directory
      shell: bash
      run: |
        echo "Copying custom C-API and CMake files..."
        cp custom_files/newrllama_capi.h backend/llama.cpp/
        cp custom_files/newrllama_capi.cpp backend/llama.cpp/
        # We overwrite the original CMakeLists.txt with our custom one
        cp custom_files/CMakeLists.txt.custom backend/llama.cpp/CMakeLists.txt

    # Step 3: Configure and Build
    - name: Configure and Build
      shell: bash
      run: |
        cd backend/llama.cpp
        mkdir build && cd build

        # Base CMake arguments. CRITICAL: We force a STATIC build for all dependencies.
        CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF"
        
        # On Windows, we still need to point to the vcpkg toolchain.
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # FIX for Windows: Use the correct env var and quote the path.
          CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_TOOLCHAIN_FILE=\"${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake\" -DVCPKG_TARGET_TRIPLET=x64-windows-static"
        fi
        
        echo "Configuring with CMake: $CMAKE_ARGS"
        cmake .. $CMAKE_ARGS
        
        echo "Building target 'newrllama'..."
        cmake --build . --config Release --target newrllama -- -j 2
        
    # Step 4: Prepare the artifact for release.
    # We create a clean zip file containing only the final library.
    - name: Package the artifact
      shell: bash
      run: |
        # Create a temporary 'staging' directory for packaging.
        mkdir -p staging/lib
        
        # Define the path to the compiled library.
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          LIB_PATH="backend/llama.cpp/build/bin/Release/${{ matrix.lib_name }}"
        else
          LIB_PATH="backend/llama.cpp/build/bin/${{ matrix.lib_name }}"
        fi

        # Copy the library into the staging directory.
        echo "Copying $LIB_PATH to staging/lib/"
        cp "$LIB_PATH" staging/lib/

        # Create the zip archive.
        echo "Creating zip archive: ${{ matrix.artifact_name }}"
        cd staging
        zip -r ../${{ matrix.artifact_name }} .
        cd ..

    # Step 5: Upload the final zip file to the GitHub Release.
    # This uses a pre-made action to handle the upload securely.
    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        # The GITHUB_TOKEN is automatically provided by GitHub Actions.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The URL to upload to is automatically found from the 'release' event.
        upload_url: ${{ github.event.release.upload_url }}
        # Path to the zip file we just created.
        asset_path: ./${{ matrix.artifact_name }}
        # The name the file will have on the release page.
        asset_name: ${{ matrix.artifact_name }}
        # The content type of the file.
        asset_content_type: application/zip 