name: Test Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        use-public-rspm: true
    
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: newrllama4
        extra-packages: any::covr
        needs: coverage
    
    - name: Test coverage
      run: |
        # Move to package directory
        cd newrllama4
        
        # Install package
        R CMD INSTALL .
        
        # Run coverage with covr
        Rscript -e "
          library(covr)
          
          # Since this is a package with C++ backend that needs runtime loading,
          # we focus on testing R code coverage
          coverage <- package_coverage(
            path = '.',
            type = 'tests',
            quiet = FALSE
          )
          
          print(coverage)
          
          # Upload to codecov
          codecov(coverage = coverage, token = Sys.getenv('CODECOV_TOKEN'))
        "
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false